function createRaceState(){return{active:false,playerDist:0,cpuDist:0,speed:0,lane:0,steer:0,finish:3300,last:0,offroad:false,cpuCarId:8}}
race=createRaceState();
canRace=function(){return state.unlockedParts.length>=20||state.raceTickets>0||race?.active||ui.raceResult!==null};
function roadCurve(d){return Math.sin(d/120)*.85+Math.sin(d/250+1)*.58+Math.sin(d/53)*.2}
function initRaceCanvas(){let c=$('#raceCanvas');if(!c)return;drawRace(c.getContext('2d'),c.width,c.height,race);if(!c._bound){c._bound=true;let sx=null;c.ontouchstart=e=>sx=e.touches[0].clientX;c.ontouchmove=e=>{if(sx==null)return;race.steer=Math.max(-1,Math.min(1,(e.touches[0].clientX-sx)/75))};c.ontouchend=()=>{sx=null;race.steer=0}}}
function startRace(){if(state.unlockedParts.length<20&&state.raceTickets<=0)return toast('レース券がありません');if(state.unlockedParts.length<20){state.raceTickets--;save()}race=createRaceState();race.cpuCarId=(CARS.filter(c=>c.id!==state.selectedCarId).sort(()=>Math.random()-.5)[0]||CARS[7]).id;ui.raceResult=null;render();setTimeout(()=>{let o=$('#raceOverlay');if(!o)return;let n=3;o.textContent=n;beep();let t=setInterval(()=>{n--;if(n>0){o.textContent=n;beep()}else{clearInterval(t);o.textContent='GO!';rev();startRaceAudio();race.active=true;race.last=performance.now();setTimeout(()=>{if(o)o.textContent=''},500);raceAnim=requestAnimationFrame(raceLoop)}},700)},0)}
function raceLoop(ts){if(!race.active||ui.screen!=='race')return stopRace();let c=$('#raceCanvas');if(!c)return stopRace();let dt=Math.min(.033,(ts-race.last)/1000||.016);race.last=ts;let curve=roadCurve(race.playerDist+130);race.lane+=race.steer*dt*2.7+curve*dt*.62;race.lane=Math.max(-1.6,Math.min(1.6,race.lane));race.offroad=Math.abs(race.lane)>.92;let target=race.offroad?27:57;race.speed+=(target-race.speed)*dt*1.8;race.playerDist+=race.speed*dt;race.cpuDist+=(51.5+Math.sin(ts/700)*2.4)*dt;updateRaceAudio();drawRace(c.getContext('2d'),c.width,c.height,race);if($('#spd'))$('#spd').textContent=Math.round(race.speed*4.5);if($('#prog'))$('#prog').textContent=Math.min(100,Math.round(race.playerDist/race.finish*100))+'%';if($('#status'))$('#status').textContent=race.offroad?'⚠️ OFF ROAD':'🏁 ON TRACK';if(race.playerDist>=race.finish||race.cpuDist>=race.finish){let win=race.playerDist>=race.finish&&race.playerDist>=race.cpuDist;stopRace();ui.raceResult=win?'win':'lose';win?success():alertTone();render();return}raceAnim=requestAnimationFrame(raceLoop)}
function drawRace(ctx,w,h,r){let hor=h*.3;ctx.clearRect(0,0,w,h);let sky=ctx.createLinearGradient(0,0,0,hor);sky.addColorStop(0,'#04101d');sky.addColorStop(.6,'#0c4677');sky.addColorStop(1,'#f28c40');ctx.fillStyle=sky;ctx.fillRect(0,0,w,hor);ctx.fillStyle='#0c1b11';ctx.fillRect(0,hor,w,h-hor);let prev=null;for(let i=0;i<=72;i++){let z=i/72,y=hor+Math.pow(z,1.68)*(h-hor),look=r.playerDist+(1-z)*1300,center=w/2+roadCurve(look)*w*.26*(1-z*.18)-r.lane*w*.21*z,half=38+Math.pow(z,1.16)*w*.39,cur={y,center,half};if(prev){let alt=(Math.floor(look/25)%2)===0;ctx.beginPath();ctx.moveTo(prev.center-prev.half,prev.y);ctx.lineTo(prev.center+prev.half,prev.y);ctx.lineTo(cur.center+cur.half,cur.y);ctx.lineTo(cur.center-cur.half,cur.y);ctx.closePath();ctx.fillStyle=alt?'#2c3035':'#24292e';ctx.fill();let curb=Math.max(4,half*.05);ctx.fillStyle=alt?'#f5f5f5':'#e42e2e';ctx.beginPath();ctx.moveTo(prev.center-prev.half,prev.y);ctx.lineTo(prev.center-prev.half-curb,prev.y);ctx.lineTo(cur.center-cur.half-curb,cur.y);ctx.lineTo(cur.center-cur.half,cur.y);ctx.closePath();ctx.fill();ctx.beginPath();ctx.moveTo(prev.center+prev.half,prev.y);ctx.lineTo(prev.center+prev.half+curb,prev.y);ctx.lineTo(cur.center+cur.half+curb,cur.y);ctx.lineTo(cur.center+cur.half,cur.y);ctx.closePath();ctx.fill()}prev=cur}let rel=r.cpuDist-r.playerDist;if(rel>0&&rel<1200){let z=1-rel/1200,py=hor+Math.pow(Math.max(z,.06),1.68)*(h-hor),center=w/2+roadCurve(r.playerDist+rel)*w*.22*(1-z*.18)-r.lane*w*.18*z,cw=42+z*118,ch=cw*.48,img=carImages.get(r.cpuCarId);if(img?.complete)ctx.drawImage(img,center-cw/2,py-ch,cw,ch)}let cw=w*.39,ch=cw*.47,x=w/2-cw/2+r.steer*w*.055,img=carImages.get(state.selectedCarId);if(img?.complete){ctx.save();ctx.translate(x+cw/2,h-ch*.62);ctx.rotate(r.steer*.07);ctx.drawImage(img,-cw/2,-ch,cw,ch);ctx.restore()}if(r.offroad){ctx.fillStyle='rgba(255,80,30,.12)';ctx.fillRect(0,0,w,h)}}
function startRaceAudio(){try{let a=ac(),m=a.createGain();m.gain.value=vol();m.connect(a.destination);let s=snd(),o=a.createOscillator(),o2=a.createOscillator();o.type=s.wave;o2.type=s.id.includes('ev')?'sine':'triangle';o.connect(m);o2.connect(m);o.start();o2.start();let b=a.createBuffer(1,a.sampleRate*2,a.sampleRate),arr=b.getChannelData(0);for(let i=0;i<arr.length;i++)arr[i]=Math.random()*2-1;let wind=a.createBufferSource(),wg=a.createGain(),f=a.createBiquadFilter();wind.buffer=b;wind.loop=true;f.type='highpass';f.frequency.value=900;wind.connect(f);f.connect(wg);wg.connect(m);wg.gain.value=.001;wind.start();raceAudio={a,m,o,o2,wg,wind}}catch{}}
function updateRaceAudio(){if(!raceAudio)return;let s=snd(),t=raceAudio.a.currentTime,f=s.base+race.speed*4.7;raceAudio.o.frequency.setTargetAtTime(f,t,.04);raceAudio.o2.frequency.setTargetAtTime(f*s.harm*.5,t,.04);raceAudio.wg.gain.setTargetAtTime(Math.max(.001,race.speed*.0008),t,.05);if(race.offroad&&Math.random()<.12)tone(900,.04,'sawtooth',.22);if(s.id==='antilag'&&Math.random()<.018)tone(95,.055,'square',.6)}
function stopRace(){cancelAnimationFrame(raceAnim);if(race)race.active=false;if(raceAudio){try{raceAudio.o.stop();raceAudio.o2.stop();raceAudio.wind.stop()}catch{}raceAudio=null}}

if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
save();render();
