function render(){const root=$('#app');if(!root)return;root.innerHTML=(V[ui.screen]||V.home)();bind();if(ui.screen==='race'&&canRace())requestAnimationFrame(initRaceCanvas)}
function go(x){if(x!=='race')stopRace();ui.screen=x;if(x==='study'&&!ui.studyTask)ui.studyTask=state.studyTasks[0]?.id||null;click();render()}
function toast(x){ui.toast=x;render();setTimeout(()=>{if(ui.toast===x){ui.toast='';render()}},1600)}

function bind(){document.querySelectorAll('[data-go]').forEach(e=>e.onclick=()=>go(e.dataset.go));document.querySelectorAll('[data-task]').forEach(e=>e.onclick=()=>{ui.studyTask=+e.dataset.task;click();render()});document.querySelectorAll('[data-mode]').forEach(e=>e.onclick=()=>{if(ui.studyRun||ui.breakRun)return toast('タイマーを止めてから切り替えてね');ui.timerMode=e.dataset.mode;click();render()});document.querySelectorAll('[data-time]').forEach(e=>e.onclick=()=>{if(ui.timerMode==='break')ui.breakMin=+e.dataset.time;else ui.studyMin=+e.dataset.time;click();render()});document.querySelectorAll('[data-clean-min]').forEach(e=>e.onclick=()=>{ui.cleanMin=+e.dataset.cleanMin;click();render()});document.querySelectorAll('[data-clean-count]').forEach(e=>e.onclick=()=>{ui.cleanCount=Math.max(0,ui.cleanCount+(+e.dataset.cleanCount));click();render()});document.querySelectorAll('[data-prep]').forEach(e=>e.onclick=()=>togglePrep(+e.dataset.prep));document.querySelectorAll('[data-car]').forEach(e=>e.onclick=()=>{state.selectedCarId=+e.dataset.car;save();rev();render()});document.querySelectorAll('[data-vol]').forEach(e=>e.onclick=()=>{state.soundVolume=e.dataset.vol;save();click();render()});document.querySelectorAll('[data-preview]').forEach(e=>e.onclick=()=>previewSound(e.dataset.preview));document.querySelectorAll('[data-use-sound]').forEach(e=>e.onclick=()=>{state.selectedSound=e.dataset.useSound;save();previewSound(state.selectedSound);render()});document.querySelectorAll('[data-part]').forEach(e=>e.onclick=()=>buyPart(+e.dataset.part));document.querySelectorAll('[data-del-study]').forEach(e=>e.onclick=()=>{state.studyTasks=state.studyTasks.filter(t=>t.id!==+e.dataset.delStudy);save();render()});document.querySelectorAll('[data-del-prep]').forEach(e=>e.onclick=()=>{state.prepItems=state.prepItems.filter(t=>t.id!==+e.dataset.delPrep);save();render()});document.querySelectorAll('[data-ticket]').forEach(e=>e.onclick=()=>{state.raceTickets+=+e.dataset.ticket;save();success();toast(`レース券 +${e.dataset.ticket}`)});document.querySelectorAll('[data-point]').forEach(e=>e.onclick=()=>{let n=+e.dataset.point;let r=award(n);success();toast(`+${n}pt`);if(r.sound)setTimeout(()=>{ui.overlay={type:'sound',sound:r.sound};render()},600);else if(r.grand)setTimeout(()=>{ui.overlay={type:'grand'};render()},600)});document.querySelectorAll('[data-act]').forEach(e=>e.onclick=()=>ACT[e.dataset.act]?.());document.querySelectorAll('[data-steer]').forEach(e=>{let l=e.dataset.steer==='left';e.onpointerdown=()=>race.steer=l?-1:1;e.onpointerup=e.onpointerleave=e.onpointercancel=()=>race.steer=0});let voice=$('#voice');if(voice)voice.onchange=()=>{state.timerVoice=voice.checked;save()}}
const ACT={unlockParent(){if($('#code')?.value===state.parentCode){ui.parentUnlocked=true;success();render()}else{alertTone();toast('コードが違います')}},addStudy(){let n=$('#studyName')?.value.trim();if(!n)return;state.studyTasks.push({id:state.nextStudyTaskId++,name:n});save();render()},addPrep(){let n=$('#prepName')?.value.trim();if(!n)return;state.prepItems.push({id:state.nextPrepId++,name:n,done:false});save();render()},resetPrep(){state.prepItems=state.prepItems.map(i=>({...i,done:false}));save();render()},startStudy,pauseStudy:()=>{ui.studyRun=false;clearInterval(studyTimer);render()},resumeStudy:()=>{ui.studyRun=true;runStudy();render()},resetStudy:()=>{ui.studyRun=false;ui.studyLeft=0;clearInterval(studyTimer);render()},startBreak,pauseBreak:()=>{ui.breakRun=false;clearInterval(breakTimer);render()},resumeBreak:()=>{ui.breakRun=true;runBreak();render()},resetBreak:()=>{ui.breakRun=false;ui.breakLeft=0;clearInterval(breakTimer);render()},quickBreak(){ui.overlay=null;ui.screen='study';ui.timerMode='break';ui.breakMin=5;ui.breakLeft=0;render()},returnStudy,closeOverlay(){ui.overlay=null;ui.screen='home';render()},closeOverlayOnly(){ui.overlay=null;render()},startClean,pauseClean:()=>{ui.cleanRun=false;clearInterval(cleanTimer);stopCanCan();render()},resumeClean:()=>{ui.cleanRun=true;startCanCan();runClean();render()},resetClean:()=>{ui.cleanRun=false;ui.cleanLeft=0;ui.cleanCount=0;clearInterval(cleanTimer);stopCanCan();render()},startPrep(){ui.prepRun=true;ui.prepLeft=300;runPrep();render()},stopPrep(){ui.prepRun=false;clearInterval(prepTimer);render()},finishPrep(){finishPrep()},startRace(){startRace()}}

function startStudy(){ui.studyLeft=ui.studyMin*60;ui.studyRun=true;speechMinute=null;rev();runStudy();render()}
function runStudy(){clearInterval(studyTimer);studyTimer=setInterval(()=>{ui.studyLeft--;if(ui.studyLeft>0&&ui.studyLeft%60===0){let m=ui.studyLeft/60;minuteCue(m)}if(ui.studyLeft<=0){clearInterval(studyTimer);ui.studyRun=false;let pts=ui.studyMin*10;let r=award(pts,'study');success();ui.overlay={type:'studyDone',pts,sound:r.sound,grand:r.grand};render();return}render()},1000)}
function minuteCue(m){pleasant();if(state.timerVoice)say(`残り ${m} 分`)}
function startBreak(){ui.breakLeft=ui.breakMin*60;ui.breakRun=true;pleasant();runBreak();render()}
function runBreak(){clearInterval(breakTimer);breakTimer=setInterval(()=>{ui.breakLeft--;if(ui.breakLeft>0&&ui.breakLeft%60===0){pleasant();if(state.timerVoice)say(`休憩 あと ${ui.breakLeft/60} 分`)}if(ui.breakLeft<=0){clearInterval(breakTimer);ui.breakRun=false;pleasant();ui.overlay={type:'breakDone'};render();return}render()},1000)}
function returnStudy(){let n=3;ui.overlay={type:'count',n};beep();render();clearInterval(returnTimer);returnTimer=setInterval(()=>{n--;if(n>0){ui.overlay={type:'count',n};beep();render()}else{clearInterval(returnTimer);ui.overlay=null;ui.timerMode='study';startStudy()}},850)}
function startClean(){ui.cleanLeft=ui.cleanMin*60;ui.cleanRun=true;ui.cleanCount=0;startCanCan();runClean();render()}
function runClean(){clearInterval(cleanTimer);cleanTimer=setInterval(()=>{ui.cleanLeft--;if(ui.cleanLeft===60&&state.timerVoice)say('残り 1 分');if(ui.cleanLeft===30&&state.timerVoice)say('残り 30 秒');if(ui.cleanLeft<=10&&ui.cleanLeft>0)beep();if(ui.cleanLeft<=0){clearInterval(cleanTimer);ui.cleanRun=false;stopCanCan();finishClean();return}render()},1000)}
function finishClean(){let best=state.cleanBest[ui.cleanMin]||0,record=ui.cleanCount>best;if(record)state.cleanBest[ui.cleanMin]=ui.cleanCount;state.cleanHistory.push({date:dayKey(),minutes:ui.cleanMin,count:ui.cleanCount});let base=ui.cleanMin*10,bonus=record&&ui.cleanCount>0?20:0;let r=award(base+bonus,'clean');success();ui.overlay={type:'cleanDone',count:ui.cleanCount,base,record,sound:r.sound,grand:r.grand};save();render()}
function togglePrep(id){state.prepItems=state.prepItems.map(i=>i.id===id?{...i,done:!i.done}:i);click();save();render()}
function runPrep(){clearInterval(prepTimer);prepTimer=setInterval(()=>{ui.prepLeft--;if(ui.prepLeft===60&&state.timerVoice)say('準備チャレンジ 残り 1 分');if(ui.prepLeft<=0){ui.prepRun=false;clearInterval(prepTimer);alertTone();render()}else render()},1000)}
function finishPrep(){let all=state.prepItems.length&&state.prepItems.every(i=>i.done);if(!all)return;let pts=ui.prepRun&&ui.prepLeft>0?50:30;ui.prepRun=false;clearInterval(prepTimer);let r=award(pts,'prep');success();state.prepItems=state.prepItems.map(i=>({...i,done:false}));save();ui.overlay=r.sound?{type:'sound',sound:r.sound}:r.grand?{type:'grand'}:null;toast(`準備完了 +${pts}pt`);render()}
function buyPart(id){let p=PARTS.find(x=>x.id===id);if(!p||state.unlockedParts.includes(id))return;if(state.points<p.cost){alertTone();return toast('ポイントが足りません')}state.points-=p.cost;state.unlockedParts.push(id);save();success();render()}
